// Protobuf-generated implementation file.
// Re-generated for the Velox project.

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

#ifndef PROTOBUF_C_request_2eproto__INCLUDED
#define PROTOBUF_C_request_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Request Request;
typedef struct Request__Socket Request__Socket;
typedef struct Request__Connect Request__Connect;
typedef struct Request__Close Request__Close;
typedef struct Request__Recvfrom Request__Recvfrom;
typedef struct Request__Sendto Request__Sendto;
typedef struct Request__Poll Request__Poll;
typedef struct Request__Select Request__Select;
typedef struct Request__Getpeername Request__Getpeername;
