/* Protobuf-generated file. Re-generated for the Velox project. */

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "request.pb-c.h"
void   request__socket__init
                     (Request__Socket         *message)
{
  static const Request__Socket init_value = REQUEST__SOCKET__INIT;
  *message = init_value;
}
void   request__connect__init
                     (Request__Connect         *message)
{
  static const Request__Connect init_value = REQUEST__CONNECT__INIT;
  *message = init_value;
}
void   request__close__init
                     (Request__Close         *message)
{
  static const Request__Close init_value = REQUEST__CLOSE__INIT;
  *message = init_value;
}
void   request__recvfrom__init
                     (Request__Recvfrom         *message)
{
  static const Request__Recvfrom init_value = REQUEST__RECVFROM__INIT;
  *message = init_value;
}
void   request__sendto__init
                     (Request__Sendto         *message)
{
  static const Request__Sendto init_value = REQUEST__SENDTO__INIT;
  *message = init_value;
}
void   request__poll__init
                     (Request__Poll         *message)
{
  static const Request__Poll init_value = REQUEST__POLL__INIT;
  *message = init_value;
}
void   request__select__init
                     (Request__Select         *message)
{
  static const Request__Select init_value = REQUEST__SELECT__INIT;
  *message = init_value;
}
void   request__getpeername__init
