/* Protobuf-generated file. Re-generated for the Velox project. */

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: response.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "response.pb-c.h"
void   response__socket__init
                     (Response__Socket         *message)
{
  static const Response__Socket init_value = RESPONSE__SOCKET__INIT;
  *message = init_value;
}
void   response__connect__init
                     (Response__Connect         *message)
{
  static const Response__Connect init_value = RESPONSE__CONNECT__INIT;
  *message = init_value;
}
void   response__close__init
                     (Response__Close         *message)
{
  static const Response__Close init_value = RESPONSE__CLOSE__INIT;
  *message = init_value;
}
void   response__recvfrom__init
                     (Response__Recvfrom         *message)
{
