// Protobuf-generated implementation file.
// Re-generated for the Velox project.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

#include "request.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Request_Socket::Request_Socket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.domain_)*/0
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.protocol_)*/0} {}
struct Request_SocketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Request_SocketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Request_SocketDefaultTypeInternal() {}
  union {
    Request_Socket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Request_SocketDefaultTypeInternal _Request_Socket_default_instance_;
PROTOBUF_CONSTEXPR Request_Connect::Request_Connect(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.addr_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct Request_ConnectDefaultTypeInternal {
